name: Update Leaderboard

on:
  schedule:
    - cron: "30 10 * * *"  # каждый день в 10:30 UTC (13:30 UTC+3)
  workflow_dispatch:      # можно запустить вручную

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run script
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: python update_leaderboard.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add leaderboard.json all_tweets.json || true
          git commit -m "Auto update leaderboard [skip ci]" || echo "No changes"
          git push
