name: Update Leaderboard

on:
  schedule:
    # 10:30 по UTC+3 → 07:30 UTC
    - cron: "30 7 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        env:
          API_KEY: ${{ secrets.API_KEY }}  # твой API ключ для SocialData
        run: python update_leaderboard.py

      - name: Commit and push changes
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add leaderboard.json all_tweets.json || true
          git commit -m "Auto update leaderboard [skip ci]" || echo "No changes"
          git push
